### ISSUE TITLE
Wrong FAILED state

### ISSUE THREAD

**Issue by wernerflamme** [deimosfr/nagios-check_file_content#2]
`/usr/lib/nagios/plugins/check_file_content.pl -f /usr/lib/secchk/security-weekly.sh -i 'nfs4'
FAILED on /usr/lib/secchk/security-weekly.sh. Found only 1 on 1`

Why is this `FAILED`? I expect exactly 1 occurence of that string. Adding "-n 1" doesn't change the output. I am running this on SLES 11 SP4 with perl v5.10.0.

**Comment by deimosfr** [comment]
Thanks for the PR
